name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: static page goes via ssh
        uses: appleboy/ssh-action@v1
        with:
          host: 54.89.72.182
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: | 
                ls -a
