name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to Server and Debug
        uses: appleboy/ssh-action@v1
        with:
          host: 54.89.72.182
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
                echo "✅ Connected to server"
                cd ~/ci-cd
                chmod +x scripts/deploy.sh
                ./scripts/deploy.sh
                